name: Form sample
description: This form is used as an example
title: "Form submission"
labels: ["form1"]
assignees:
  - eliastor
body:
  - type: input
    id: contact
    validations:
      required: false
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: checkboxes
    id: agree1
    # validations:
    #   required: true
    attributes:
      label: Agree with terms
      description: Do you agree with terms
      options:
        - label: I agree with with terms 1 https://eliastor.cc/terms1
          required: true
        - label: I agree with with terms 2 https://eliastor.cc/terms2
          required: true
        - label: I read README.md [README.md](README.md) 
          required: true
  - type: dropdown
    id: accesses
    validations:
      required: true
    attributes:
      label: Access to resources
      multiple: true
      options:
        - Resource 1
        - Resource 2
        - Resource 3
        - Resource 4
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
