name: Form sample
description: This form is used as an example
title: "Form submission"
labels: ["form1"]
assignees:
  - eliastor
body:
  - type: input
    id: contact
    # validations:
    #   required: false
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com

  - type: input
    id: invitation_id
    attributes:
      label: Invitation ID
      description: If you have invintation, provide its ID here
    validations:
      required: false
  
  - type: dropdown
    id: accesses
    validations:
      required: true
    attributes:
      label: Access to resources (Multiple selections are possible)
      multiple: true
      options:
        - Resource 1
        - Resource 2
        - Resource 3
        - Resource 4
  
  - type: checkboxes
    id: terms
    # validations:
    #   required: true
    attributes:
      label: Agree with terms
      description: Do you agree with terms
      options:
        - label: "I agree with with terms 1 https://eliastor.cc/terms1"
          required: true
        - label: "I agree with with terms 2 https://eliastor.cc/terms2"
          required: true
        - label: "I read README.md [README.md](README.md)" 
          required: true
        - label: I read and agree [Code of Conduct](https://example.com).
          required: true
