name: Cloud resources cleaner

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

concurrency: "${{github.workflow}}"

jobs:
  on-workflow-completion:
    uses: ./.github/workflows/aps-clean.yml
    with:
      config-path: "blah"

# on fail send notification