name: Wipe cloud reasource out

on:
  workflow_run:
    workflows: ["*"]
    types:
      - completed

concurrency: "${{github.workflow}}"

jobs:
  on-workflow-completion:
    runs-on: ubuntu-latest
    steps:
      - name: Run Your Specific Action
        run: |
          # Cleaning cloud resources
          echo "Cleaning cloud resources"

# on fail send notification