name: infra-run
on:
  workflow_dispatch:
    inputs:
      reqid:
        description: 'request id'
        required: false
        type: string
concurrency: "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd && ls -hla
          ls -hla /home/runner/
      - name: Run APS
        uses: ./.github/workflows/aps-start.yml
      - name: do the job
        run: echo "do the job!"
