name: infra-run
on:
  workflow_dispatch:
    inputs:
      reqid:
        description: 'request id'
        required: false
        type: string
concurrency: "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
jobs:
  token_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $(echo "${{ github.TOKEN }}" | base64)
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          pwd && tree .github
  
  aps-start:
    uses: ./.github/workflows/aps-start.yml
    with:
      config-path: "blah"

  deploy:
    runs-on: ubuntu-latest
    needs: ["aps-start"]
    steps:
      - name: APS background task
        # uses: ./github/workflows/aps-watch.yml
        # with:
        #   arg: dfdfd
        run: (while sleep 1; do echo "executing"; done) &
      
      - name: do the job
        run: echo "do the job!"
  clean:
    needs: ["deploy"]
    uses: ./.github/workflows/aps-clean.yml
    with:
      config-path: aaa
