name: infra-test
on:
  workflow_dispatch:
    inputs:
      reqid:
        description: 'request id'
        required: false
        type: string
concurrency: "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
jobs:
  aps-provision-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Install APS
        run: "# install aps"
      - name: "provision account"
        run: "# aps provision testacc1"
    
  provision-test-infra:
    runs-on: ubuntu-latest
    steps:
      - name: HashiCorp - Setup Terraform
        # You may pin to the exact commit or the version.
        # uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: "v1.5.6"
          terraform_wrapper: true
          
      - uses: actions/checkout@v3
      - run: echo "${{ github.workflow }}-${{ github.head_ref ||  github.ref }}-${{ github.event.inputs.reqid }}"
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
