name: infra-run
on:
  workflow_dispatch:
    inputs:
      reqid:
        description: 'request id'
        required: false
        type: string
concurrency: "{{ github.head_ref ||  github.ref || inputs.reqid }}"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo ${{ inputs.reqid }}
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
