on: workflow_dispatch
name: Test of programmatic access to secrets
env:
  __ALL_SECRETS: ${{ toJSON(secrets) }}

jobs:
  programmatic_access:
    runs-on: ubuntu-slim
    environment: dev
    steps:
      - name: Available keys
        run: echo "${__ALL_SECRETS}" | jq 'keys[] '
      - name: get sample value
        run: echo "${__ALL_SECRETS}" | jq -r '.SECRET1' | base32 - 
